name: timetable_flutter
description: TimeTableApp.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.1
  freezed: ^2.1.0+1
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
